### ISSUE TITLE
filter_fn default works across variants and effects

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cohorts#100]
@tavinathanson I'm a bit confused about the behavior of the `filter_fn` arg of `Cohort`. Should this a function from `FilterableVariant` -> bool? or `FilterableEffect`?

For example something like 

```
def qcfilter(filterable_variant):
    somatic_stats = variant_stats_from_variant(filterable_variant.variant,
                                               filterable_variant.variant_metadata)

     ...
```

works with either since both have a `variant` field and `variant_metadata` but if we ever looks at exclusive properties, `load_variants` or `load_effects` would fail.

**Comment by tavinathanson** [comment]
@arahuja so you're asking what happens if we have a filter specific for `FilterableEffects` and pass it into `load_variants`? I guess that wouldn't work, but why would we pass it in there? (Maybe some more examples that you're concerned about would help?) As for the reverse case (`load_effects` breaking because a field isn't in `FilterableVariant`), that should never happen since `FilterableEffect` extends `FilterableVariant`.

**Comment by arahuja** [comment]
> so you're asking what happens if we have a filter specific for FilterableEffects and pass it into load_variants

Yes, just clarifying, this should not work then?

> As for the reverse case (load_effects breaking because a field isn't in FilterableVariant), that should never happen since FilterableEffect extends FilterableVariant

Ah ok, didn't see this.

I guess my example is I have something like this:

```
def effect_gene_filter(filterable_effect):
    return filterable_effect.effect.gene_id in GENE_IDS
```

**Comment by tavinathanson** [comment]
Gotcha. Yeah, that shouldn't work and I assume will throw an error that `FilterableVariant` has no `effect` attribute. Does that seem reasonable?

**Comment by tavinathanson** [comment]
@arahuja can this be closed?
