### ISSUE TITLE
strip_column_names warning when running tests

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/cohorts#89]
When I run `nosetests test` locally, I see:

```
tavi@tavi-machine-clone:~/cohorts$ nosetests test
................../home/tavi/cohorts/cohorts/utils.py:136: UserWarning: Warning: strip_column_names (if run) would introduce duplicate names. Reverting column names to the original.
  warnings.warn(warn_str)
............
----------------------------------------------------------------------
```

@jburos is this expected?

**Comment by jburos** [comment]
Yes this is intentional. I put a test in to make sure (a) the warning
prints, and (b) names aren't changed.

But, the code to capture the warning doesn't actually work since the
warnings are a little messed up.

We should probably make an issue to review / revisit logging and warning
strategy in general . One element of that will be to catch this warning
correctly.

**Comment by tavinathanson** [comment]
Cool, I think this can be that issue.
